using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace HW_3_REDUX
{
    internal class architecture
    {
        /*
* Project: Architecture
* Developer: Brian Teruya
* Purpose: create architecture for homework assignments
* last modified: 2/10/2026
* last modification: finalizations of HW 3
*/
        //==============================
        //Architecture from Homework 2
        //==============================
        /*
         * Welcome to Pirate Monopoly!
         * 
         * Get player information
         * Player Name----------------------------
         * in order for the game to start. the console will ask for a player's name
         * once you type in a name (whatever you want it to be)
         * the console will store that name into a string variable within a player object
         *
         * 
         * Player piece type and placement-----------------------------
         * Pieces-----------------------------
         * a pirate hat
         * an eye patch
         * the steering wheel
         * the plank
         * Jeffrey the parrot
         * a treasure chest
         * a cannon
         * legally distinct jack sparrow with a bottle of a non alcoholic substance
         * 
         * after getting the name, the console will list and ask for the player
         * to pick one of the pieces
         * this will also be put in a variable within the player object
         * 
         * placement-----------------------------
         * based on the dice roll.
         * each player will press enter -- when its their turn -- to roll the dice
         * whatever the number is, that determines where the piece will go and the spot
         * where the piece will land on.
         * 
         * Games Won-----------------------------
         * there is no winning in pirate monopoly
         * ... only surviving
         * 
         * Games Lost-----------------------------
         * game ends when all but one player goes bankrupt (ran out of treasure bucks)
         * the game will check the player objects to see how much treasure bucks they have in the variable.
         * 
        /* Player action items-----------------------------
         * Buy/sell Property
         * your “property”, instead of buildings, are your crew members. Each property spot on the board
         * will have a crew member with the cost it takes to have them join your crew.
         * they all have different rates they pay you based on what treasure they find.
         * you can choose to buy and keep, or sell them.
         * 
         * House - Crewmate
         * Hotel - Pirate Ship
         * 
         * Show player information-----------------------------
         * you can show your information, what crewmembers you have, how many wins and losses you 
         * have so far in the session, and how much money you have.
         * there will be a method with an option to look at those stats. When selected, 
         *your game name, money status, piece type, number of crewmembers or ships , all will be listed in the console.
         *
         *
        /* Game Engine Actions-----------------------------
         * Setup Game-----------------------------
                 * at the start of a game, the console will prompt for the player's name.
                 * once that is received and recorded into a player object,
                 * the console will then prompt for the piece type.
                 * that will also be received and recorded into the player object
                 * 
                 * Then the game will start with each player taking turns rolling the dice
                 * all cards , properties, and other game items will be setup and placed in their respective spots
                 * each player will start with a set amount of treasure bucks,
                 * and that value will be stored into the player object as well.

         * Determine Winner/Loser/Ties-----------------------------
         * Winners win if they still have money when everyone else goes bankrupt
         *if 2 or more people go bankrupt at the same time, it’s a tie
         * Validate player choices-----------------------------
         * If a player doesnt have enough money to buy a crewmate, then so be it.
         * Console will check the player object to see how much money they have when making 
         * monetary decisions.
         * Turns and prompting-----------------------------
         * each players turn will go like this
         * 1: they roll the dice and go that many spaces
         *the dice is generated by a random number generator, starting from 1 and ending at 12
         * 2: if wherever they land has a feature to it, they can choose to partake in that feature (if that 
         * option is feasible, otherwise they MUST utilize the feature EX pick a card)
         *getting to that place is where the Console uses a Movement method that uses a math
         *equation, before moving the piece ingame
         * 
         */


        //==============================
        //Homework 3
        //==============================
        /* 
         * We need to start making constructors and variables for our architecture.
         * thats the point of this homework
         */
        //Player data information
        //player piece
        //this determines what the player will be using as a piece
        protected string pieceType = "";
        //our player will choose from one of these pieces
        protected List<string> pieces = new List<string>()
        {
            "a pirate hat",
            "an eye patch",
            "the steering wheel",
            "the plank",
            "Jeffrey the parrot",
            "a treasure chest",
            "a cannon",
            "legally distinct jack sparrow with a bottle of a non alcoholic substance"
        };
        //player name
        private string playerName = "";//stored here when received

        //Games won/lost ratio
        //I decided doing a win loss ratio would be more effective for this game
        private int gamesWon = 0;
        private int gamesLost = 0;
        //a method will include these two when needed to be displayed
        //player action items
        //player money
        protected int pMoney = 1500; //starting money
        protected int pMoneydebt = 0;//if money is owed. value will change as the game continues


        //game engine actions
        //game setup
        protected List<string> property_names = new List<string>()
        {
            "Da Bob",
            "Davy Jones's Locker",
            "Tortuga",
            "Skull Island",
            "Shipwreck Cove",
            "Port Royal",
            "Blackbeard's Castle",
            "The Kraken's Lair",
        };//this is the list of properties we can buy
        protected List<string> advanceship_names = new List<string>()
        {
            "the crow's nest",
            "the galley",
            "the brig",
            "the captain's quarters",
            "the hold",
            "the deck",
            "the forecastle",
            "the poop deck"
        };//this is the list of locations we can advance to when we get certain cards
          //chance and community chest cards
        protected List<string> Chancecards = new List<string>()
        {
            "advance to the start landlubber! (collect 200 treasure bucks)", //1
            "yer sharp eyes are needed! advance to the crow's nest immediately!", //2
            "advance to the Tortuga! An adventure awaits", //3
            "advance to the galley! maybe ye can grab some (200) treasure bucks if you pass go!", //4
            "take a ride to the captain's quarters! snag 200 treasure bucks if you pass go!", //5
            "advance to the nearest island location or ship location! if owned, pay the owner twice the rental! if not, buy it and snag territory!!!", //6
            " advance to the nearest ship location! if owned, throw the dice and pay the owner 10 times that amount! if unowned claim it!!!", //7
            "turn back 3 spaces I left some treasure!!!", //8
            "for yer honest work, I'll give ye 50 treasure bucks", //9
            "ye have a gambling win! collect 150 treasure bucks", //10
            "pay the bank 15 treasure bucks", //11
            "you lost the worst bet and now have to clean the poop deck! pay each landlubber (player) 50 trasure bucks", //12
            "ye have ta help yer people!!! pay 20 treasure bucks for each crewmember", //13
            "I DONT CARE MATEY JUST GO TO JAIL!", //14
            "I care matey! get out of jail free when needed!", //15
            "Ships aren't free! pay 40 treasure bucks for each pirate ship you own." //16
        };//16 total cards
        protected List<string> Communitychestcards = new List<string>()
        {
            "advance to the start landlubber! (collect 200 treasure bucks)", //1
            "yer life insurance matures! collect 100 treasure bucks", //2
            "ye have a birthday! collect 10 treasure bucks", //3
            "yer tax refund came in the sea mail! collect 200 treasure bucks", //4
            "even a pirate has stocks to hold! collect 45 treasure bucks", //5
            "small treasure is still treasure! collect 20 treasure bucks", //6
            "for yer troubles! 25 treasure bucks to yer name", //7
            "yer father was a famous pirate?!? have 100 treasure bucks!!!", //8
            "merry christmas! collect 100 treasure bucks", //9
            "THE MASTER PLUNDERER!!! Collect 50 treasure bucks from every landlubber (player) here!!!", //10
            "ye have a gambling win! collect 50 treasure bucks", //11
            "how did ye lose yer treasure scallywag?!? lose 100 treasure bucks", //12
            "ye have a gambling loss! lose 150 treasure bucks", //13
            "crewmates aren't free! pay 20 treasure bucks per crewmember on your territories", //14
            "I DONT CARE MATEY JUST GO TO JAIL!", //15
            "I care matey! get out of jail free when needed!" //16

        };//16 total cards

        //determine winner/loser/ties
        protected bool playerwin; //determines winner
        protected bool playerloss; //determines loser(s)
                                   //validate player choices


        //turns and prompting
        protected bool Turn;//true = it is your turn
        //false = not your turn anymore.
        protected Random diceroller = new Random(); //our dice roller.
        //goes from 2 - 12
    }

}
