using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Brian_Teruya___HW_2
{
    internal class Architecture
    {
        //==============================
        //Homework 2
        //==============================
        /*
         * Welcome to Pirate Monopoly!
         * 
         * Get player information
         * Player Name----------------------------
         * in order for the game to start. the console will ask for a player's name
         * once you type in a name (whatever you want it to be)
         * the console will store that name into a string variable within a player object
         *
         * 
         * Player piece type and placement-----------------------------
         * Pieces-----------------------------
         * a pirate hat
         * an eye patch
         * the pirate ship
         * the plank
         * Jeffrey the parrot
         * a treasure chest
         * a cannon
         * legally distinct jack sparrow with a bottle of a non alcoholic substance
         * 
         * after getting the name, the console will list and ask for the player
         * to pick one of the pieces
         * this will also be put in a variable within the player object
         * 
         * placement-----------------------------
         * based on the dice roll.
         * each player will press enter -- when its their turn -- to roll the dice
         * whatever the number is, that determines where the piece will go and the spot
         * where the piece will land on.
         * 
         * Games Won-----------------------------
         * there is no winning in pirate monopoly
         * ... only surviving
         * 
         * Games Lost-----------------------------
         * game ends when all but one player goes bankrupt (ran out of treasure bucks)
         * the game will check the player objects to see how much treasure bucks they have in the variable.
         * 
        /* Player action items-----------------------------
         * Buy/sell Property
         * your “property”, instead of buildings, are your crew members. Each property spot on the board
         * will have a crew member with the cost it takes to have them join your crew.
         * they all have different rates they pay you based on what treasure they find.
         * you can choose to buy and keep, or sell them.
         * 
         * Show player information-----------------------------
         * you can show your information, what crewmembers you have, how many wins and losses you 
         * have so far in the session, and how much money you have.
         * there will be a method with an option to look at those stats. When selected, 
         *your game name, money status, piece type, crewmembers, all will be listed in the console.
         *
         *
        /* Game Engine Actions-----------------------------
         * Setup Game-----------------------------
                 * at the start of a game, the console will prompt for the player's name.
                 * once that is received and recorded into a player object,
                 * the console will then prompt for the piece type.
                 * that will also be received and recorded into the player object
                 * 
                 * Then the game will start with each player taking turns rolling the dice
                 * all cards , properties, and other game items will be setup and placed in their respective spots
                 * each player will start with a set amount of treasure bucks,
                 * and that value will be stored into the player object as well.

         * Determine Winner/Loser/Ties-----------------------------
         * Winners win if they still have money when everyone else goes bankrupt
         *if 2 or more people go bankrupt at the same time, it’s a tie
         * Validate player choices-----------------------------
         * If a player doesn't have enough money to buy a crewmate, then so be it.
         * Console will check the player object to see how much money they have when making 
         * monetary decisions.
         * Turns and prompting-----------------------------
         * each players turn will go like this
         * 1: they roll the dice and go that many spaces
         *the dice is generated by a random number generator, starting from 1 and ending at 12
         * 2: if wherever they land has a feature to it, they can choose to partake in that feature (if that 
         * option is feasible, otherwise they MUST utilize the feature EX pick a card)
         *getting to that place is where the Console uses a Movement method that uses a math
         *equation, before moving the piece in-game
         * 
         */


    }
}
